name: CI

# env:
#   POETRY_VERSION: "1.8.2"
#   POETRY_HOME: "/opt/poetry"

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v4

      - name: setup poetry
        uses: ./.github/actions/setup-poetry
        with:
          poetry-version: 1.8.2

      - name: setup python
        uses: ./.github/actions/setup-python
        with:
          python-version: 3.12.5

      # - name: setup python
      #   id: setup-python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: 3.12.5
      #     cache: poetry

      # - name: get info
      #   run: |
      #     poetry env info
      #     which python

      # - name: check lockfile
      #   run: poetry check

      # - name: install 
      #   if: steps.setup-python.outputs.cache-hit != 'true'
      #   run: poetry install
      
      - name: ruff check
        id: ruff-check
        continue-on-error: true
        run: poetry run ruff check
      
      - name: ruff format
        id: ruff-format
        continue-on-error: true
        run: poetry run ruff format --diff

      - name: ruff failure
        if: steps.ruff-check.outcome != 'success' || steps.ruff-format.outcome != 'success'
        run: false
      
      - name: pytest
        run: CI=1 poetry run pytest tests
