name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Setup Poetry
        uses: ./.github/actions/setup-poetry
        with:
          poetry-version: 1.8.2

      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          python-version: 3.12.5

      - name: Pre-commit
        uses: ./.github/actions/pre-commit

      - name: Run Pytest
        run: CI=1 poetry run pytest --color=yes tests
